-- 版权案件基本信息表
CREATE TABLE `copyright_case_info` (
    `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `case_code` VARCHAR(50) NOT NULL COMMENT '我方文号/系统编号',
    `case_name` VARCHAR(200) NOT NULL COMMENT '案件名称',
    `case_type` VARCHAR(100) DEFAULT NULL COMMENT '案件类型',
    `client_case_code` VARCHAR(50) DEFAULT NULL COMMENT '客户文号',
    `client_id` INT(11) DEFAULT NULL COMMENT '客户ID，关联customer(id)',
    `business_type` VARCHAR(100) DEFAULT NULL COMMENT '业务类型',
    `process_item` VARCHAR(100) DEFAULT NULL COMMENT '处理事项',
    `case_status` VARCHAR(100) DEFAULT NULL COMMENT '案件状态',
    `entrust_date` DATE DEFAULT NULL COMMENT '委案日期',
    `business_dept_id` INT(11) DEFAULT NULL COMMENT '承办部门ID，关联department(id)',
    `business_user_ids` VARCHAR(200) DEFAULT NULL COMMENT '业务人员ID（多选，逗号分隔，关联user表）',
    `application_mode` VARCHAR(100) DEFAULT NULL COMMENT '申请方式',
    `application_type` VARCHAR(100) DEFAULT NULL COMMENT '申请类型',
    `country` VARCHAR(100) DEFAULT NULL COMMENT '国家(地区)',
    `case_flow` VARCHAR(100) DEFAULT NULL COMMENT '案件流向',
    `source_country` VARCHAR(100) DEFAULT NULL COMMENT '案源国',    
    `open_date` DATE DEFAULT NULL COMMENT '开卷日',
    `application_no` VARCHAR(50) DEFAULT NULL COMMENT '受理号',
    `application_date` DATE DEFAULT NULL COMMENT '受理日',
    `registration_no` VARCHAR(50) DEFAULT NULL COMMENT '登记号',
    `registration_date` DATE DEFAULT NULL COMMENT '登记日',
    `certificate_no` VARCHAR(50) DEFAULT NULL COMMENT '证书号',
    `expire_date` DATE DEFAULT NULL COMMENT '届满日',
    `start_stage` VARCHAR(100) DEFAULT NULL COMMENT '起始阶段',
    `is_expedited` VARCHAR(100) DEFAULT NULL COMMENT '加快级别',
    `is_subsidy_agent` TINYINT(1) DEFAULT 0 COMMENT '是否代办资助(1是0否)',
    `is_material_available` TINYINT(1) DEFAULT 0 COMMENT '有无材料(1有0无)',
    `remarks` TEXT COMMENT '案件备注',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_case_code` (`case_code`),
    KEY `idx_business_dept_id` (`business_dept_id`),
    KEY `idx_client_id` (`client_id`),
    KEY `idx_application_no` (`application_no`),
    KEY `idx_registration_no` (`registration_no`),
    CONSTRAINT `fk_copyright_case_info_business_dept` FOREIGN KEY (`business_dept_id`) REFERENCES `department`(`id`),
    CONSTRAINT `fk_copyright_case_info_client` FOREIGN KEY (`client_id`) REFERENCES `customer`(`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = '版权案件基本信息表';


-- 版权案件处理事项表
CREATE TABLE `copyright_case_task` (
    `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `copyright_case_info_id` INT(11) NOT NULL COMMENT '关联版权案件ID',
    -- 基本信息
    `task_item` VARCHAR(200) NOT NULL COMMENT '处理事项',
    `task_status` VARCHAR(100) DEFAULT NULL COMMENT '处理状态',
    `case_stage` VARCHAR(100) DEFAULT NULL COMMENT '案件阶段',
    -- 期限管理
    `internal_deadline` DATE DEFAULT NULL COMMENT '内部期限',
    `client_deadline` DATE DEFAULT NULL COMMENT '客户期限',
    `official_deadline` DATE DEFAULT NULL COMMENT '官方期限',
    -- 人员管理
    `handler_id` INT(11) DEFAULT NULL COMMENT '处理人ID，关联user表',
    `external_handler_id` INT(11) DEFAULT NULL COMMENT '对外处理人ID，关联user表',
    `supervisor_id` INT(11) DEFAULT NULL COMMENT '核稿人ID，关联user表',
    -- 日期管理
    `first_draft_date` DATE DEFAULT NULL COMMENT '初稿日',
    `final_draft_date` DATE DEFAULT NULL COMMENT '定稿日',
    `return_date` DATE DEFAULT NULL COMMENT '返稿日',
    `completion_date` DATE DEFAULT NULL COMMENT '完成日',
    `send_to_firm_date` DATE DEFAULT NULL COMMENT '送合作所日',
    `internal_final_date` DATE DEFAULT NULL COMMENT '内部定稿日',
    -- 创建和修改信息
    `creator_id` INT(11) DEFAULT NULL COMMENT '创建人ID，关联user表',
    `creation_date` DATE DEFAULT NULL COMMENT '创建日期',
    `modifier_id` INT(11) DEFAULT NULL COMMENT '修改人ID，关联user表',
    `modification_date` DATE DEFAULT NULL COMMENT '修改日期',
    -- 其他信息
    `is_urgent` TINYINT(1) DEFAULT 0 COMMENT '是否紧急 0否 1是',
    `task_rule_count` VARCHAR(20) DEFAULT NULL COMMENT '处理事项系数',
    `translation_word_count` INT DEFAULT NULL COMMENT '翻译字数',
    `contract_number` VARCHAR(100) DEFAULT NULL COMMENT '合同编号',
    `remarks` TEXT COMMENT '备注',
    -- 系统字段
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `idx_copyright_case_info_id` (`copyright_case_info_id`),
    KEY `idx_handler_id` (`handler_id`),
    KEY `idx_external_handler_id` (`external_handler_id`),
    KEY `idx_supervisor_id` (`supervisor_id`),
    KEY `idx_creator_id` (`creator_id`),
    KEY `idx_modifier_id` (`modifier_id`),
    CONSTRAINT `fk_copyright_task_case` FOREIGN KEY (`copyright_case_info_id`) REFERENCES `copyright_case_info`(`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_copyright_task_handler` FOREIGN KEY (`handler_id`) REFERENCES `user`(`id`) ON DELETE SET NULL,
    CONSTRAINT `fk_copyright_task_external_handler` FOREIGN KEY (`external_handler_id`) REFERENCES `user`(`id`) ON DELETE SET NULL,
    CONSTRAINT `fk_copyright_task_supervisor` FOREIGN KEY (`supervisor_id`) REFERENCES `user`(`id`) ON DELETE SET NULL,
    CONSTRAINT `fk_copyright_task_creator` FOREIGN KEY (`creator_id`) REFERENCES `user`(`id`) ON DELETE SET NULL,
    CONSTRAINT `fk_copyright_task_modifier` FOREIGN KEY (`modifier_id`) REFERENCES `user`(`id`) ON DELETE SET NULL
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = '版权案件处理事项表';

-- 版权案件申请人关联表
CREATE TABLE `copyright_case_applicant` (
    `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `copyright_case_info_id` INT(11) NOT NULL COMMENT '关联版权案件ID',
    -- 基本信息
    `case_type` VARCHAR(50) DEFAULT NULL COMMENT '案件类型（专利/商标/版权，逗号分隔）',
    `applicant_type` VARCHAR(20) DEFAULT NULL COMMENT '申请人类型（个人/单位/其他）',
    `entity_type` VARCHAR(20) DEFAULT NULL COMMENT '实体类型（大实体/小实体/微实体）',
    `name_cn` VARCHAR(100) DEFAULT NULL COMMENT '名称(中文)',
    `name_en` VARCHAR(100) DEFAULT NULL COMMENT '名称(英文)',
    `name_xing_cn` VARCHAR(50) DEFAULT NULL COMMENT '名称/姓(中文)',
    `name_xing_en` VARCHAR(50) DEFAULT NULL COMMENT '名称/姓(英文)',
    `is_first_contact` TINYINT(1) DEFAULT 0 COMMENT '是否第一联系人（0否1是）',
    `is_receipt_title` TINYINT(1) DEFAULT 0 COMMENT '作为收据抬头（0否1是）',
    `receipt_title` VARCHAR(100) DEFAULT NULL COMMENT '申请人收据抬头（勾选作为收据抬头时填写）',
    `credit_code` VARCHAR(50) DEFAULT NULL COMMENT '申请人统一社会信用代码（勾选作为收据抬头时填写）',
    -- 其它字段
    `contact_person` VARCHAR(50) DEFAULT NULL COMMENT '联系人',
    `phone` VARCHAR(30) DEFAULT NULL COMMENT '电话',
    `email` VARCHAR(100) DEFAULT NULL COMMENT '邮件',
    `province` VARCHAR(50) DEFAULT NULL COMMENT '省份',
    `city_cn` VARCHAR(50) DEFAULT NULL COMMENT '城市(中文)',
    `city_en` VARCHAR(50) DEFAULT NULL COMMENT '城市(英文)',
    `district` VARCHAR(50) DEFAULT NULL COMMENT '行政区划',
    `postcode` VARCHAR(20) DEFAULT NULL COMMENT '邮编',
    `address_cn` VARCHAR(200) DEFAULT NULL COMMENT '街道地址(中文)',
    `address_en` VARCHAR(200) DEFAULT NULL COMMENT '街道地址(英文)',
    `department_cn` VARCHAR(100) DEFAULT NULL COMMENT '部门/楼层(中文)',
    `department_en` VARCHAR(100) DEFAULT NULL COMMENT '部门/楼层(英文)',
    `id_type` VARCHAR(50) DEFAULT NULL COMMENT '证件类型',
    `id_number` VARCHAR(100) DEFAULT NULL COMMENT '证件号',
    `is_fee_reduction` TINYINT(1) DEFAULT 0 COMMENT '费用减案（0否1是）',
    `fee_reduction_start` DATE DEFAULT NULL COMMENT '费用减案有效期起',
    `fee_reduction_end` DATE DEFAULT NULL COMMENT '费用减案有效期止',
    `fee_reduction_code` VARCHAR(100) DEFAULT NULL COMMENT '备案证件号',
    `cn_agent_code` VARCHAR(100) DEFAULT NULL COMMENT '中国总委托编号',
    `pct_agent_code` VARCHAR(100) DEFAULT NULL COMMENT 'PCT总委托编号',
    `is_fee_monitor` TINYINT(1) DEFAULT 0 COMMENT '监控年费（0否1是）',
    `country` VARCHAR(100) DEFAULT NULL COMMENT '国家(地区)',
    `nationality` VARCHAR(100) DEFAULT NULL COMMENT '国籍',
    `business_license` VARCHAR(200) DEFAULT NULL COMMENT '营业执照（文件路径）',
    `remark` TEXT COMMENT '备注',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `idx_copyright_case_info_id` (`copyright_case_info_id`),
    CONSTRAINT `fk_copyright_applicant_case` FOREIGN KEY (`copyright_case_info_id`) REFERENCES `copyright_case_info`(`id`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = '版权案件申请人关联表';

-- 版权案件申请人相关上传文件表
CREATE TABLE `copyright_case_applicant_file` (
    `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `copyright_case_applicant_id` INT(11) NOT NULL COMMENT '关联版权案件申请人ID',
    `copyright_case_info_id` INT(11) NOT NULL COMMENT '关联版权案件ID',
    `file_type` VARCHAR(50) NOT NULL COMMENT '文件类型（费减证明/总委托书/附件）',
    `file_name` VARCHAR(200) NOT NULL COMMENT '文件名',
    `file_path` VARCHAR(300) NOT NULL COMMENT '文件存储路径',
    `file_size` BIGINT DEFAULT NULL COMMENT '文件大小（字节）',
    `mime_type` VARCHAR(100) DEFAULT NULL COMMENT '文件MIME类型',
    `upload_user_id` INT(11) DEFAULT NULL COMMENT '上传人ID，关联user表',
    `official_issue_date` DATE DEFAULT NULL COMMENT '官方发文日（可选）',
    `remarks` TEXT COMMENT '备注说明',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '上传时间',
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `idx_copyright_case_applicant_id` (`copyright_case_applicant_id`),
    KEY `idx_copyright_case_info_id` (`copyright_case_info_id`),
    KEY `idx_upload_user_id` (`upload_user_id`),
    CONSTRAINT `fk_copyright_applicant_file_applicant` FOREIGN KEY (`copyright_case_applicant_id`) REFERENCES `copyright_case_applicant`(`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_copyright_applicant_file_case` FOREIGN KEY (`copyright_case_info_id`) REFERENCES `copyright_case_info`(`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_copyright_applicant_file_user` FOREIGN KEY (`upload_user_id`) REFERENCES `user`(`id`) ON DELETE SET NULL
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = '版权案件申请人相关上传文件表';

-- 版权案件作者关联表（版权中的"发明人"对应"作者"）
CREATE TABLE `copyright_case_author` (
    `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `copyright_case_info_id` INT(11) NOT NULL COMMENT '关联版权案件ID',
    `name_cn` VARCHAR(50) NOT NULL COMMENT '中文名',
    `name_en` VARCHAR(50) DEFAULT NULL COMMENT '英文名',
    `job_no` VARCHAR(30) DEFAULT NULL COMMENT '工号',
    `xing_cn` VARCHAR(50) DEFAULT NULL COMMENT '名称/姓(中文)',
    `xing_en` VARCHAR(50) DEFAULT NULL COMMENT '名称/姓(英文)',
    `ming_cn` VARCHAR(50) DEFAULT NULL COMMENT '名(中文)',
    `ming_en` VARCHAR(50) DEFAULT NULL COMMENT '名(英文)',
    `nationality` VARCHAR(50) DEFAULT NULL COMMENT '国籍',
    `country` VARCHAR(50) DEFAULT NULL COMMENT '国家(地区)',
    `is_main_author` TINYINT(1) DEFAULT 0 COMMENT '是否为主要作者(0否1是)',
    `province` VARCHAR(50) DEFAULT NULL COMMENT '省份',
    `city_cn` VARCHAR(50) DEFAULT NULL COMMENT '城市(中文)',
    `city_en` VARCHAR(50) DEFAULT NULL COMMENT '城市(英文)',
    `address_cn` VARCHAR(200) DEFAULT NULL COMMENT '街道地址(中文)',
    `address_en` VARCHAR(200) DEFAULT NULL COMMENT '街道地址(英文)',
    `department_cn` VARCHAR(100) DEFAULT NULL COMMENT '部门/楼层(中文)',
    `department_en` VARCHAR(100) DEFAULT NULL COMMENT '部门/楼层(英文)',
    `email` VARCHAR(100) DEFAULT NULL COMMENT '邮件',
    `id_number` VARCHAR(50) DEFAULT NULL COMMENT '证件号码',
    `phone` VARCHAR(30) DEFAULT NULL COMMENT '座机',
    `qq` VARCHAR(30) DEFAULT NULL COMMENT 'QQ',
    `mobile` VARCHAR(30) DEFAULT NULL COMMENT '手机',
    `postcode` VARCHAR(20) DEFAULT NULL COMMENT '邮编',
    `remark` TEXT COMMENT '备注',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `idx_copyright_case_info_id` (`copyright_case_info_id`),
    CONSTRAINT `fk_copyright_author_case` FOREIGN KEY (`copyright_case_info_id`) REFERENCES `copyright_case_info`(`id`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = '版权案件作者关联表';

-- 版权案件代理机构关联表
CREATE TABLE `copyright_case_agency` (
    `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `copyright_case_info_id` INT(11) NOT NULL COMMENT '关联版权案件ID',
    `agency_id` INT(11) NOT NULL COMMENT '关联代理机构ID',
    `agency_agent_id` INT(11) DEFAULT NULL COMMENT '关联代理人ID',
    `agency_contact_id` INT(11) DEFAULT NULL COMMENT '关联联系人ID',
    `agency_name_cn` VARCHAR(200) DEFAULT NULL COMMENT '代理机构名称(中文)',
    `agency_code` VARCHAR(100) DEFAULT NULL COMMENT '代理机构代码',
    `agent_name_cn` VARCHAR(50) DEFAULT NULL COMMENT '代理人姓名(中文)',
    `agent_license_no` VARCHAR(50) DEFAULT NULL COMMENT '代理人执业证号',
    `contact_name` VARCHAR(50) DEFAULT NULL COMMENT '联系人姓名',
    `contact_phone` VARCHAR(30) DEFAULT NULL COMMENT '联系人电话',
    `contact_email` VARCHAR(100) DEFAULT NULL COMMENT '联系人邮箱',
    `remark` TEXT COMMENT '备注',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `idx_copyright_case_info_id` (`copyright_case_info_id`),
    KEY `idx_agency_id` (`agency_id`),
    KEY `idx_agency_agent_id` (`agency_agent_id`),
    KEY `idx_agency_contact_id` (`agency_contact_id`),
    CONSTRAINT `fk_copyright_case_agency_case` FOREIGN KEY (`copyright_case_info_id`) REFERENCES `copyright_case_info`(`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_copyright_case_agency_agency` FOREIGN KEY (`agency_id`) REFERENCES `agency`(`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_copyright_case_agency_agent` FOREIGN KEY (`agency_agent_id`) REFERENCES `agency_agent`(`id`) ON DELETE SET NULL,
    CONSTRAINT `fk_copyright_case_agency_contact` FOREIGN KEY (`agency_contact_id`) REFERENCES `agency_contact`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='版权案件代理机构关联表';

-- 版权案件官费表
CREATE TABLE `copyright_case_official_fee` (
    `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `copyright_case_info_id` INT(11) NOT NULL COMMENT '关联版权案件ID',
    `sequence_no` INT(11) DEFAULT NULL COMMENT '序号',
    `fee_name` VARCHAR(200) NOT NULL COMMENT '费用名称',
    `fee_reduction_type` ENUM('基础费用', '单位费减', '个人费减') DEFAULT '基础费用' COMMENT '费减类型',
    `currency` VARCHAR(10) DEFAULT 'CNY' COMMENT '币别',
    `amount` DECIMAL(12, 2) DEFAULT NULL COMMENT '金额',
    `quantity` INT(11) DEFAULT 1 COMMENT '数量',
    `actual_currency` VARCHAR(10) DEFAULT 'CNY' COMMENT '实际币别',
    `actual_amount` DECIMAL(12, 2) DEFAULT NULL COMMENT '实际金额',
    `receivable_date` DATE DEFAULT NULL COMMENT '应收日期',
    `received_date` DATE DEFAULT NULL COMMENT '实收日期',
    `official_deadline` DATE DEFAULT NULL COMMENT '官方期限',
    `paid_date` DATE DEFAULT NULL COMMENT '实付日期',
    `task_item` VARCHAR(100) DEFAULT NULL COMMENT '处理事项',
    `is_verified` TINYINT(1) DEFAULT 0 COMMENT '是否核查(1是0否)',
    `remarks` TEXT COMMENT '备注',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `idx_copyright_case_info_id` (`copyright_case_info_id`),
    KEY `idx_fee_name` (`fee_name`),
    KEY `idx_receivable_date` (`receivable_date`),
    KEY `idx_official_deadline` (`official_deadline`),
    KEY `idx_task_item` (`task_item`),
    CONSTRAINT `fk_copyright_official_fee_case` FOREIGN KEY (`copyright_case_info_id`) REFERENCES `copyright_case_info`(`id`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = '版权案件官费表';

-- 版权案件文件表
CREATE TABLE `copyright_case_file` (
    `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `copyright_case_info_id` INT(11) NOT NULL COMMENT '关联版权案件ID',
    `file_type` VARCHAR(50) NOT NULL COMMENT '文件类型（版权申请书/作品样本/身份证明/委托书/审查意见/答复意见/其他）',
    `file_name` VARCHAR(200) NOT NULL COMMENT '文件名',
    `file_path` VARCHAR(300) NOT NULL COMMENT '文件存储路径',
    `file_size` BIGINT DEFAULT NULL COMMENT '文件大小（字节）',
    `mime_type` VARCHAR(100) DEFAULT NULL COMMENT '文件MIME类型',
    `upload_user_id` INT(11) DEFAULT NULL COMMENT '上传人ID，关联user表',
    `official_issue_date` DATE DEFAULT NULL COMMENT '官方发文日（可选）',
    `remarks` TEXT COMMENT '备注说明',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '上传时间',
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `idx_copyright_case_info_id` (`copyright_case_info_id`),
    KEY `idx_file_type` (`file_type`),
    KEY `idx_upload_user_id` (`upload_user_id`),
    CONSTRAINT `fk_copyright_case_file_case` FOREIGN KEY (`copyright_case_info_id`) REFERENCES `copyright_case_info`(`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_copyright_case_file_user` FOREIGN KEY (`upload_user_id`) REFERENCES `user`(`id`) ON DELETE SET NULL
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = '版权案件文件表';