CREATE TABLE `patent_case_info` (
    `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `case_code` VARCHAR(50) NOT NULL COMMENT '我方文号/系统编号',
    `case_name` VARCHAR(200) NOT NULL COMMENT '案件名称',
    `case_name_en` VARCHAR(200) DEFAULT NULL COMMENT '英文名称',
    `business_dept_id` INT(11) DEFAULT NULL COMMENT '承办部门ID，关联department(id)',
    `open_date` DATE DEFAULT NULL COMMENT '开卷日期',
    `client_case_code` VARCHAR(50) DEFAULT NULL COMMENT '客户文号',
    `process_item` VARCHAR(100) DEFAULT NULL COMMENT '处理事项',
    `client_id` INT(11) DEFAULT NULL COMMENT '客户ID，关联customer(id)',
    `business_type` VARCHAR(100) DEFAULT NULL COMMENT '业务类型',
    `entrust_date` DATE DEFAULT NULL COMMENT '委案日期',
    `case_status` VARCHAR(100) DEFAULT NULL COMMENT '案件状态',
    `same_day_apply` TEXT COMMENT '同日申请(JSON/逗号分隔)',
    `same_day_submit` TEXT COMMENT '同日递交(JSON/逗号分隔)',
    `agent_rule` VARCHAR(20) DEFAULT NULL COMMENT '代理费规则(自定义/纯包/按项)',
    `remarks` TEXT COMMENT '案件备注',
    `application_no` VARCHAR(50) DEFAULT NULL COMMENT '申请号',
    `application_date` DATE DEFAULT NULL COMMENT '申请日',
    `publication_no` VARCHAR(50) DEFAULT NULL COMMENT '公开号',
    `publication_date` DATE DEFAULT NULL COMMENT '公开日',
    `handler_id` INT(11) DEFAULT NULL COMMENT '处理人ID，关联user(id)',
    `announcement_no` VARCHAR(50) DEFAULT NULL COMMENT '公告号',
    `announcement_date` DATE DEFAULT NULL COMMENT '公告日',
    `certificate_no` VARCHAR(50) DEFAULT NULL COMMENT '证书号',
    `expire_date` DATE DEFAULT NULL COMMENT '属满日',
    `enter_substantive_date` DATE DEFAULT NULL COMMENT '进入实审日',
    `application_mode` VARCHAR(100) DEFAULT NULL COMMENT '申请方式',
    `business_user_ids` VARCHAR(200) DEFAULT NULL COMMENT '业务人员ID（多选，逗号分隔，关联user表）',
    `business_assistant_ids` VARCHAR(200) DEFAULT NULL COMMENT '业务助理ID（多选，逗号分隔，关联user表）',
    `project_leader_id` INT(11) DEFAULT NULL COMMENT '项目负责人ID，关联user(id)',
    `application_type` VARCHAR(100) DEFAULT NULL COMMENT '申请类型',
    `is_allocated` TINYINT(1) DEFAULT 1 COMMENT '是否配案(1是0否)',
    `country` VARCHAR(100) DEFAULT NULL COMMENT '国家(地区)',
    `case_flow` VARCHAR(100) DEFAULT NULL COMMENT '案件流向',
    `start_stage` VARCHAR(100) DEFAULT NULL COMMENT '起始阶段',
    `client_status` VARCHAR(100) DEFAULT NULL COMMENT '客户状态',
    `source_country` VARCHAR(100) DEFAULT NULL COMMENT '案源国',
    `other_options` TEXT COMMENT '其他复选项(JSON/逗号分隔)',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_case_code` (`case_code`),
    KEY `idx_business_dept_id` (`business_dept_id`),
    KEY `idx_client_id` (`client_id`),
    KEY `idx_handler_id` (`handler_id`),
    KEY `idx_project_leader_id` (`project_leader_id`),
    CONSTRAINT `fk_patent_case_info_business_dept` FOREIGN KEY (`business_dept_id`) REFERENCES `department`(`id`),
    CONSTRAINT `fk_patent_case_info_client` FOREIGN KEY (`client_id`) REFERENCES `customer`(`id`),
    CONSTRAINT `fk_patent_case_info_handler` FOREIGN KEY (`handler_id`) REFERENCES `user`(`id`),
    CONSTRAINT `fk_patent_case_info_project_leader` FOREIGN KEY (`project_leader_id`) REFERENCES `user`(`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = '专利案件表';