-- 客户信息表
CREATE TABLE `customer` (
    `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `customer_code` VARCHAR(50) DEFAULT NULL COMMENT '客户编号（系统自动生成）',
    `customer_name_cn` VARCHAR(100) NOT NULL COMMENT '客户名称(中)',
    `customer_name_en` VARCHAR(100) DEFAULT NULL COMMENT '客户名称(英)',
    `company_leader` VARCHAR(50) DEFAULT NULL COMMENT '公司负责人',
    `email` VARCHAR(100) DEFAULT NULL COMMENT '邮件',
    `business_staff_id` INT(11) DEFAULT NULL COMMENT '业务人员，关联user(id)',
    `internal_signer` VARCHAR(50) DEFAULT NULL COMMENT '内部签署人',
    `external_signer` VARCHAR(50) DEFAULT NULL COMMENT '外部签署人',
    `process_staff_id` INT(11) DEFAULT NULL COMMENT '流程人员，关联user(id)',
    `customer_level` VARCHAR(20) DEFAULT NULL COMMENT '客户等级',
    `address` VARCHAR(200) DEFAULT NULL COMMENT '地址',
    `bank_name` VARCHAR(100) DEFAULT NULL COMMENT '开户银行',
    `deal_status` VARCHAR(20) DEFAULT NULL COMMENT '成交状态',
    `project_leader_id` INT(11) DEFAULT NULL COMMENT '项目负责人，关联user(id)',
    `remark` TEXT COMMENT '备注',
    `case_type_patent` TINYINT(1) DEFAULT 0 COMMENT '案件类型-专利',
    `case_type_trademark` TINYINT(1) DEFAULT 0 COMMENT '案件类型-商标',
    `case_type_copyright` TINYINT(1) DEFAULT 0 COMMENT '案件类型-版权',
    `phone` VARCHAR(30) DEFAULT NULL COMMENT '电话',
    `industry` VARCHAR(200) DEFAULT NULL COMMENT '所属行业（多选，逗号分隔）',
    `creator` VARCHAR(50) DEFAULT NULL COMMENT '创建人',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
    `internal_signer_phone` VARCHAR(30) DEFAULT NULL COMMENT '内部签署人电话',
    `external_signer_phone` VARCHAR(30) DEFAULT NULL COMMENT '外部签署人电话',
    `billing_address` VARCHAR(200) DEFAULT NULL COMMENT '账单地址',
    `credit_level` VARCHAR(20) DEFAULT NULL COMMENT '信管等级',
    `address_en` VARCHAR(200) DEFAULT NULL COMMENT '英文地址',
    `bank_account` VARCHAR(50) DEFAULT NULL COMMENT '银行账号',
    `customer_id_code` VARCHAR(50) DEFAULT NULL COMMENT '客户代码',
    `new_case_manager_id` INT(11) DEFAULT NULL COMMENT '新申请配案主管，关联user(id)',
    `fax` VARCHAR(30) DEFAULT NULL COMMENT '传真',
    `customer_source` VARCHAR(50) DEFAULT NULL COMMENT '客户来源',
    `internal_signer_email` VARCHAR(100) DEFAULT NULL COMMENT '内部签署人邮箱',
    `external_signer_email` VARCHAR(100) DEFAULT NULL COMMENT '外部签署人邮箱',
    `delivery_address` VARCHAR(200) DEFAULT NULL COMMENT '收货地址',
    `sign_date` DATE DEFAULT NULL COMMENT '客户签约日期',
    `public_email` VARCHAR(100) DEFAULT NULL COMMENT '本所业务公共邮箱',
    `tax_id` VARCHAR(50) DEFAULT NULL COMMENT '纳税人识别号',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_customer_code` (`customer_code`),
    KEY `idx_customer_name_cn` (`customer_name_cn`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = '客户信息表';

INSERT INTO customer (customer_name_cn, customer_name_en, company_leader, email, business_staff_id, internal_signer, external_signer, process_staff_id, customer_level, address, bank_name, deal_status, project_leader_id, remark, case_type_patent, case_type_trademark, case_type_copyright, phone, industry, creator, internal_signer_phone, external_signer_phone, billing_address, credit_level, address_en, bank_account, customer_id_code, new_case_manager_id, fax, customer_source, internal_signer_email, external_signer_email, delivery_address, sign_date, public_email, tax_id, created_at) VALUES ('测试客户', 'Test Customer', '张三', 'test@example.com', 1, '李四', '王五', 2, '一般客户', '广州市天河区', '中国银行', '是', 3, '这是一个测试客户', 1, 1, 0, '020-12345678', '地产,制造业,互联网', 'admin', '020-87654321', '13800138000', '广州市天河区某路', '高度信誉', 'Guangzhou, China', '6222021234567890', 'KH20240517001', 4, '020-88888888', '客户介绍', 'lisi@example.com', 'wangwu@example.com', '广州市天河区收货点', '2024-05-17', 'public@example.com', '91440101MA5XXXXXX', NOW());
